---
version: 3

images:
  base_image: 
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  system:
    - git
    - curl
  python:
    - jmespath==0.10.0
    - requests
  galaxy:
    collections:
      - name: community.general
        version: "10.4.0"
