---
version: 3

images:
  base_image: 
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy:
    collections:
      - infra.controller_configuration
  python:
    - ansible
    - requests
  system:
    - python3-pip
    - git
